### ISSUE TITLE
Carthage stalls at check out?

### ISSUE THREAD

**Issue by Marini83** [ainame/Swift-WebP#1]
Hello,

First off would like to thank you for working on WebP as it's still at its infancy!  I tried to use carthage but it hangs around checkout, possibly has to do with github?  Not to sure.

Thanks

**Comment by ainame** [comment]
Thanks your trying, this project is very infancy as you said.
I'll check it at tonight.

**Comment by Marini83** [comment]
Thank you! Do you think the encoding works at a reasonable speed for iPhone 6 for instance?

**Comment by ainame** [comment]
Maybe, those problem has solved in my environment. And I replaced v0.0.1 version by new one. 
Please try again.

> Do you think the encoding works at a reasonable speed for iPhone 6 for instance?

I think image encoding process is almost slow in general, but Core Image framework or other Apple's framework have many optimization for iPhone's hardware then it enable app to fast encoding, so Swift-WebP would be slow, because it have no optimization for iPhone.

I will use Swift-WebP in macOS mainly.
Please try benchmarking in your iPhone.

**Comment by Marini83** [comment]
Hello, seems when I clone it the libwebp folder is empty. I am assuming I should create a cartfile? 

Thanks!

**Comment by ainame** [comment]
It seem to be fail git submodule command. Please paste verbose log into your gist, and share it here.

```
carthage bootstrap --verbose
```

**Comment by ainame** [comment]
Ah, how do you install Swift-WebP?
Please try to use carthage with Cartfile.

Cartfile

```
github "ainame/Swift-WebP"
```

**Comment by Marini83** [comment]
Hello, here's my gist. I don't know why it's not adding the framework to Swift-WebP? 

https://gist.github.com/Marini83/d15071d1e0721bcd96f0312058fe6c2b

Yes that seems to be  correct, I'm entering it as `github "ainame/Swift-WebP"`

**Comment by ainame** [comment]
Hello, I've seen it.  I seem that it is succeeded of installation.

>  I don't know why it's not adding the framework to Swift-WebP?

Please read this https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

**Comment by Marini83** [comment]
Hello , thank you for your help!    I tried again following what's on the link, however it seems that liwebp is not being added, not too sure why that is happening?  for instance I keep getting these: 
`No such file or directory: 'GithubLibraries/upload s3 github/Swift-WebP/libwebp/src/dec/vp8.c'`

**Comment by ainame** [comment]
Well..., please report me more information about your environments or steps to reproduce this error in my environment. Such as, your Xcode version, your macOS version, commands, etc...

And, this project make a dynamic framework about libweb **wrapper**, but it doesn't add libwebp directly, and then you can use only `WebP` module like following links.

https://github.com/ainame/Swift-WebP/blob/master/iOS%20Example/Sources/ViewController.swift#L10

**Comment by Marini83** [comment]
Hello, these are the steps

`git clone https://github.com/ainame/Swift-WebP.git`
`vim Cartfile`
Enter `github "ainame/Swift-WebP"` in `Cartfile`
`carthage update`
Results in ....
`*** Fetching Swift-WebP
*** Checking out Swift-WebP at "v0.0.1"
*** xcodebuild output can be found in /var/folders/8h/8mqz31496m138qvgh2cn1rjh0000gn/T/carthage-xcodebuild.4vJWbE.log
*** Building scheme "WebP macOS" in WebP.xcworkspace
*** Building scheme "WebP iOS" in WebP.xcworkspace`
gettings warnings like so `warning: variable 'sum_left' may be uninitialized when used here [-Wconditional-uninitialized]`
I open `WebP.xcworkspace`
I drag  `Swift-WebP/Carthage/Build/iOS/WebP.framework` to `Linked Frameworks and Libraries` 
In `Build Phases` clicked on `New Run Script Phase` and then entered `/usr/local/bin/carthage copy-frameworks`
Under `Input Files`  I enter `$(SRCROOT)/Carthage/Build/iOS/WebP.framework`
Then I open WebP.cworkspace but when I compile there are errors such as 
`Warning: Multiple build commands for output file Library/Developer/Xcode/DerivedData/WebP-aryzjltvhnroataplewjbjnuuhok/Build/Products/Debug-iphoneos/usr/local/include/vp8li.h`
`lang: error: no such file or directory: 'Swift-WebP/libwebp/src/dec/buffer.c'`
`No such file or directory: 'Swift-WebP/libwebp/src/dec/alpha.c'`

Thanks!

**Comment by ainame** [comment]
I see. Maybe, you don't understand the usage of carthage and dynamic framework.

If you want to contribute my project and develop it, you should use this repository directly.
But, if you want to use this on **your project**, you should install this into **your project**.

Please try following steps.
1. create your iOS project
2. create `Cartfile` on it
3. exec `carthage bootstrap` command and configure project settings.
4. feel free to write your code.

**Comment by Marini83** [comment]
Hello, It works fine on the simulator but it mentions an optimization error on a real device (iPhone 6).

Thanks!
