### ISSUE TITLE
Minimum support - iOS 10?

### ISSUE THREAD

**Issue by rostopira** [ainame/Swift-WebP#3]
I installed it via Carthage, but XCode gives me error on line `import WebP`

> Module file's minimum deployment target is ios10.1 v10.1: $project_path/Carthage/Build/iOS/WebP.framework/Modules/WebP.swiftmodule/arm.swiftmodule

**Comment by ainame** [comment]
@rostopira 
Thanks you trying 👍 

Now, I update the library settings to support iOS 8.0.
You can try it!
https://github.com/ainame/Swift-WebP/releases/tag/v0.0.2
