### ISSUE TITLE
Changing encoder quality has no effect on the output file

### ISSUE THREAD

**Issue by matylla** [ainame/Swift-WebP#39]
I'm currently playing with your framework. However, changing output quality has zero effect on the output file. Can you please verify? The two configs below produce the exact same image:

```swift
var config = WebPEncoderConfig.preset(.photo, quality: 1)
var config = WebPEncoderConfig.preset(.photo, quality: 100)
```

**Comment by matylla** [comment]
Also, setting an additional `quality` property on `config` seems to have no effect:

```swift
var config = WebPEncoderConfig.preset(.photo, quality: 100)
config.quality = 100

var config = WebPEncoderConfig.preset(.photo, quality: 1)
config.quality = 1
```

**Comment by matylla** [comment]
Well, that's pretty embarrassing, but there was a bug on my side. I was overwriting the output image with another method. The quality param works just fine. Thanks for this framework and keep up the good work.

**Comment by ainame** [comment]
No worries👍 Thank you for giving this a try. Let me us if you find another issue on this library.
