### ISSUE TITLE
supported cocoapod?

### ISSUE THREAD

**Issue by song-react** [ainame/Swift-WebP#4]
I get some problem when import webp c in swift
tried modulemap, vendored frameworks

I see there a pod spec in your project , dose it works?

**Comment by ainame** [comment]
Thank you for the feedback!
Unfortunately, this library aimed at macOS firstly.
Also, I didn't maintain this project for iOS sufficiently.

I'll check this later!
But please let me know if you have more details about the errors.

**Comment by song-react** [comment]
I have success support cocoapod and Carthage in my project, here is my [configuration](https://book.dingsoung.tk/Apple/WKWebView-customize.html)

**Comment by ainame** [comment]
@DingSoung I recalled that I didn't check installation via Cocoapods. I even didn't publish it.
Maybe current `podspec` just doesn't work.

While I had a look at this project yesterday, I noticed this library didn't work on iOS.
So it would be worth to fix the crash before supporting CocoaPods...

> support iOS build (maybe broken)

😂

**Comment by joelorenz20** [comment]
Hi @ainame 

I would like to ask if there is any update on this issue?
I am currently planning to use WebP instead of APNG

I am using Swift 4 and Cocoapods.

Thanks

**Comment by ainame** [comment]
@joelorenz20 I'm sorry. I had been struggling to fix the issue >  I noticed this library didn't work on iOS
But I didn't get any outcome and besides that, I was not able to have enough time to do something due to the new 👶 . If you are keen to contribute to this project, I appreciate that.

**Comment by ainame** [comment]
Apparently, I seem to fix the problem on iOS!
So I'm going to publish this library into Cocoapods as well!

Updates: 
I couldn't make it in a short time.
I'll try it again later.

**Comment by ainame** [comment]
I decided that this project won't support CocoaPods. Because creating a podspec file for clang module and git submodule was hard enough to give up doing that.

Please use Carthage or swift package manager.
