### ISSUE TITLE
Can't get it working in Xcode 10

### ISSUE THREAD

**Issue by zippo227** [ainame/Swift-WebP#6]
I followed the Carthage instructions, but I'm getting this error. I dragged the Framework in and am not getting any syntax highlighting errors in Xcode.

ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ainame** [comment]
@zippo227 I've updated README.md.
You probably needed to run `carthage update` with `--use-submodules` flag.
If you still get that error, please let me know again with further more detailed info.

Thanks

**Comment by gholias** [comment]
Im also getting this exactly same problem. Is there a way to fix it?

**Comment by gholias** [comment]
This is the error Im getting
```
Undefined symbols for architecture x86_64:
  "WebP.WebPEncoder.init() -> WebP.WebPEncoder", referenced from:
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by zippo227** [comment]
I switched to YYImage. It works in the latest Xcode
