### ISSUE TITLE
Can not register with cocoapods?

### ISSUE THREAD

**Issue by jangsy7883** [ainame/Swift-WebP#8]
libwep is registered in the CocoaPods. 
<https://cocoapods.org/pods/libwebp>

KingfisherWebP is implemented using libwep from CocoaPods.
KingfisherWebP is registered with the CocoaPods.
<https://github.com/Yeatse/KingfisherWebP>

Can't you use this to register your cool sauce with the CocoaPods?

**Comment by ainame** [comment]
@jangsy7883 Thank you for reporting this. Let me think about this.
Do you have any usage of this library on iOS app?
Please let me know if you don't mind.

**Comment by ainame** [comment]
It turned out 😂 

> Could not build Objective-C module 'libwebp'

![screen shot 2018-10-15 at 22 49 18](https://user-images.githubusercontent.com/748949/46980471-936b7900-d0cc-11e8-8996-c39f8927a9f4.png)
